language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
script: mvn test -Delastic.hostname=$ELASTIC_HOSTNAME -Dlexigram.apikey=$LEXIGRAM_APIKEY -B
after_success:
  - mvn -Delastic.hostname=$ELASTIC_HOSTNAME -Dlexigram.apikey=$LEXIGRAM_APIKEY clean test jacoco:report coveralls:report
